### ISSUE TITLE
Problem lasnormalized LASlib

### ISSUE THREAD

**Issue by THLAB35** [r-lidar/rlas#55]
Hi,

I managed to create a dtm with no problem. On the other hand, when I want to create a dsm, I encounter a problem from the start and this error code appears:

```
cannot open file "chemin d'accès" for write
ERROR: cannot open laswriterlas with file name
LASlib internal error. See message above.
In addition: Warning message:
lasnormalize is deprecated. Use normalize_height instead. 
```

Thank you in advance for all the help you could give me.

**Comment by THLAB35** [comment]
> head(las_cat_A2)
  File.Signature File.Source.ID                                 GUID Version.Major Version.Minor               System.Identifier
1         LASF\n             10 00000000-0000-0000-0000-000000000000             1             2 LAStools (c) by rapidlasso GmbH
  Generating.Software File.Creation.Day.of.Year File.Creation.Year Header.Size Offset.to.point.data Number.of.variable.length.records
1       Global Mapper                       248               2021         227                  644                                 3
  Point.Data.Format.ID Point.Data.Record.Length Number.of.point.records X.scale.factor Y.scale.factor Z.scale.factor X.offset
1                    3                       34               286543893          0.001          0.001          0.001 256323.2
  Y.offset Z.offset    Max.X    Min.X   Max.Y   Min.Y   Max.Z  Min.Z  CRS Number.of.1st.return Number.of.2nd.return
1  5362824        0 257272.7 256323.2 5363904 5362824 183.905 117.89 2949            252261543             34282350
  Number.of.3rd.return Number.of.4th.return Number.of.5th.return
1                    0                    0                    0
                                                                                                            filename
C:\\Travail\\LiDAR\\S21088\\S21088_PointCloud_Classified_A2.las

**Comment by THLAB35** [comment]
here is the whole example:
 cannot open file 'C:/Rio Tinto/DAO/GÃ©omatique/Interne/Travail/LiDAR/S21088_SNC_Jonquiere/las_out/norm_A2/norm_256000_5362500.las' for write
ERROR: cannot open laswriterlas with file name 'C:/Rio Tinto/DAO/GÃ©omatique/Interne/Travail/LiDAR/S21088_SNC_Jonquiere/las_out/norm_A2/norm_256000_5362500.las'

**Comment by Jean-Romain** [comment]
You have only one file ?

That look like an encoding issue. Please try

```r
rlas::read.las(las_cat_A2$filename)
```

**Comment by THLAB35** [comment]
> read.las (las_cat_A2$filename)
                  X       Y       Z  gpstime Intensity ReturnNumber NumberOfReturns ScanDirectionFlag EdgeOfFlightline Classification
        1: 256385.6 5362999 130.423 320602.8     12336            1               1                 0                0              1
        2: 256385.4 5362999 130.594 320602.8     12336            1               1                 0                0              1
        3: 256385.1 5362999 130.354 320602.8     12336            1               1                 0                0              1
        4: 256384.9 5362999 130.309 320602.8     12336            1               1                 0                0              1
        5: 256384.7 5362999 130.209 320602.8     12336            1               1                 0                0              1
       ---                                                                                                                           
286543889: 257262.0 5363889 122.781 334899.6     12850            1               1                 0                0              2
286543890: 257263.5 5363895 122.551 334899.6     13621            1               1                 0                0              2
286543891: 257269.9 5363880 122.985 334899.6      6682            1               1                 0                0              1
286543892: 257262.2 5363889 122.775 334899.6     12850            1               1                 0                0              2
286543893: 257263.8 5363895 122.543 334899.6     13621            1               1                 0                0              2
           Synthetic_flag Keypoint_flag Withheld_flag ScanAngleRank UserData PointSourceID R G B
        1:          FALSE         FALSE         FALSE           -31       30            83 0 0 0
        2:          FALSE         FALSE         FALSE           -31       30            83 0 0 0
        3:          FALSE         FALSE         FALSE           -31       30            83 0 0 0
        4:          FALSE         FALSE         FALSE           -30       30            83 0 0 0
        5:          FALSE         FALSE         FALSE           -30       30            83 0 0 0
       ---                                                                                      
286543889:          FALSE         FALSE         FALSE            30        4           158 0 0 0
286543890:          FALSE         FALSE         FALSE            33        5           158 0 0 0
286543891:          FALSE         FALSE         FALSE            33        1           158 0 0 0
286543892:          FALSE         FALSE         FALSE            30        4           158 0 0 0
286543893:          FALSE         FALSE         FALSE            33        5           158 0 0 0

**Comment by Jean-Romain** [comment]
Your file is absolutely unreadable. Code, outputs, errors, comments, everything is mixed-up without any coloring and frame. There are several call to unrelated packages (e.g. `tmap`), The last thing I see is

```
In dir.create(dir, recursive = TRUE) :
  cannot create dir 'D:\lidar_out', reason 'Permission denied'
```

Which is an error on your side. If you do not have rights to wite in `D:` do not write in `D:\`.
