### ISSUE TITLE
load more than 9 extra bytes data attributes from las

### ISSUE THREAD

**Issue by JulFrey** [r-lidar/rlas#58]
Is there any possibility to load more than 9 extra bytes data fields? I can write a LAS file from lidR with more fields and load it into CloudCompare, but if I read it again into R only the first 9 attributes are loaded.

**Comment by Jean-Romain** [comment]
I is limited to 9. After 9 there is no way to parse the `select` parameters. However it should be possible to modify the code to load all the extra byte attributes.
