### ISSUE TITLE
Error when you read the header with read.lasheader(file) from copc file !

### ISSUE THREAD

**Issue by pobsteta** [r-lidar/rlas#67]
This code workd with v1.6.3 but not with v1.7.0.  [file link](https://storage.sbg.cloud.ovh.net/v1/AUTH_63234f509d6048bca3c9fd7928720ca1/ppk-lidar/SE/LHD_FXX_1042_6875_PTS_C_LAMB93_IGN69.copc.laz)

```r
lasheader <- read.lasheader("LHD_FXX_1042_6875_PTS_C_LAMB93_IGN69.copc.laz") # crash
```

**Comment by Jean-Romain** [comment]
It works all good on my computer. Please report:

- `rlas` version (latest commit ?)
- OS
- compiler used to compile `rlas`

**Comment by pobsteta** [comment]
![Capture d'écran 2023-12-03 181633](https://github.com/r-lidar/rlas/assets/932599/ca14223f-9f6c-4105-9bea-8e6c59fcda78)

**Comment by Jean-Romain** [comment]
So, it is only your COPC file that is problematic, and only on Windows. I don't have a computer running on Windows and I can't reproduce this on remote machines with your file that is too big. I'll try to investigate anyway, but won't be my priority unless you come with other problematic files.

**Comment by Jean-Romain** [comment]
I'll run rlas with some adavanced debugging tools on linux. Yet I already tested with `valgrind` and found nothing. If I find something, we will retry.

**Comment by pobsteta** [comment]
Good news. Thanks for your work.
@+

**Comment by Jean-Romain** [comment]
I pushed a temporary workaround. Please confirm it fixes your issue. Thanks
